exp_root: "/mnt/jfs/debug_sre_enrichment_new_0415_h200_from_120000"
name: "0415_qwen_image_sref_noise_query"
seed: 1764
allow_tf32: true
micro_batch_size: 16
model_precision: bf16
max_train_steps: 250000
resume_from_checkpoint: /mnt/jfs/debug_sre_enrichment_new_0415/checkpoint-120000
gradient_accumulation_steps: 1
non_activation_checkpointing_every: -1
data_record:
  enable: true
  dump:
    every: 100
    keep: 0
  path: ""
environ: null
policy: null
logging:
  log_freq: 10
  image_freq: 1000
  report_to: tensorboard
  tensorboard:
    root_dir: null
    log_dir: null
    run_name: null
checkpoint:
  dump:
    every: 2000
    keep: 0
  path: ""
parallelism:
  data_parallel_replicate_degree: 1
  tensor_parallel_with_sequenc_parallel_degree: 8
engine_target: vgo.train_engines.naive_engine
engine_config:
  data_config: configs/data/sref_ablation.yaml
  model_precision: bf16
  attention_only: true
  shard_text_encoder: false
  pipe:
    type: ""
    pipeline_path: "/data/midjourney/model_zoo/ckpts"
    dit:
      in_channels: 64
      out_channels: 64
      enable_txt_norm: true
      vec_in_dim: null
      context_in_dim: 3584
      hidden_size: 3072
      mlp_ratio: 4.0
      num_heads: 24
      depth: 60
      depth_single_blocks: 0
      axes_dim:
        - 16
        - 56
        - 56
      theta: 10000
      qkv_bias: true
      guidance_embed: false
      enable_zero_t_embed: true
    llm_encoder_type: "naive"
    llm_image_min_token: 188
    llm_image_max_token: 188
    llm_model_path: /data/midjourney/model_zoo/ckpts/Qwen2.5-VL-7B-Instruct
    dit_path: /mnt/sirui/model_zoo/Qwen-Image-Edit-2511.safetensors
    ae_path: /mnt/sirui/model_zoo/Qwen-Image-Edit-2509/vae/
    max_length: 2048
    lora: null
  optim:
    learning_rate: 6.0e-06
    weight_decay: 0.01
    epsilon: 1.0e-08
    beta1: 0.9
    beta2: 0.999
    grad_norm_clip: 1.0
    scheduler: constant_with_warmup
    warmup: 0
  policy:
    weighting_scheme: truncated_logit_normal
    shift_timesteps: true
    sref_enrichment_loss_weight: 0.1
    sref_enrichment_lower_bound: 0.0
    sref_enrichment_upper_bound: 0.8
    sref_enrichment_eps: 1.0e-06
    sref_enrichment_noise_query_only: true
    sref_enrichment_timestep_weighting: true
    sref_enrichment_timestep_weight_power: 1.0
    time_shift:
      y2: 0.6935483870967742
exp_dir: ???
logging_dir: ???
date: ???
id: ???
global_batch_size: ???
